import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hackathon Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className="m-10 text-3xl font-bold text-sky-400">Hello world!</h1>
      </main>
    </>
  )
}
