import { useGlobalContext } from '@/context'
import Head from 'next/head'
import { ReactElement, useState, useEffect } from 'react'
import { useLazyQuery } from '@apollo/client'
import { GETHACKER, GETPARTNER, GETMENTOR } from '../lib/queries'
import { IHacker, IPartner, IMentor } from '@/context/context'
import { useRouter } from 'next/router'

export const validateEmail = (email: string) => {
  return /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(
    email.toLowerCase(),
  )
}

export default function Home(): ReactElement {
  const [email, setEmail] = useState<string>('')
  const [emailError, setEmailError] = useState<string>('')
  const [
    fetchHacker,
    { loading: hackerLoading, error: hackerError, data: hackerData },
  ] = useLazyQuery<IHacker>(GETHACKER)
  const [
    fetchPartner,
    { loading: partnerLoading, error: partnerError, data: partnerData },
  ] = useLazyQuery<IPartner>(GETPARTNER)
  const [
    fetchMentor,
    { loading: mentorLoading, error: mentorError, data: mentorData },
  ] = useLazyQuery<IMentor>(GETMENTOR)
  const {
    hacker,
    setHacker,
    partner,
    setPartner,
    mentor,
    setMentor,
  } = useGlobalContext()
  const router = useRouter()

  useEffect(() => {
    if (!hackerLoading && hackerData?.getHacker) {
      setHacker(hackerData.getHacker)
      router.replace('/hacker-form')
    } else if (!partnerLoading && partnerData?.getPartner) {
      setPartner(partnerData.getPartner)
      router.replace('/partner-form')
    } else if (!mentorLoading && mentorData?.getMentor) {
      setMentor(mentorData.getMentor)
      router.replace('/mentor-form')
    }
  }, [hackerData, partnerData, mentorData])

  const handleClick = async (): Promise<void> => {
    if (!email || !validateEmail(email)) {
      setEmailError('Please enter a valid email address')
      return
    }
    const fetchHackerRes = fetchHacker({ variables: { email } })
    const fetchPartnerRes = fetchPartner({ variables: { email } })
    const fetchMentorRes = fetchMentor({ variables: { email } })
    await Promise.all([fetchHackerRes, fetchPartnerRes, fetchMentorRes])
    if (
      hackerData === undefined &&
      partnerData === undefined &&
      mentorData === undefined
    ) {
      router.replace('signup')
    }
  }

  return (
    <>
      <Head>
        <title>Hackathon Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="mx-auto mt-10 w-full max-w-[550px]">
          <h1 className="mb-3 block text-base font-medium text-xl text-[#07074D]">
            Enter your email to join the hackathon
          </h1>
          <form>
            <div className="mb-5">
              <p className="mb-5 text-red-500">{emailError}</p>
              <input
                type="email"
                name="email"
                id="email"
                placeholder="example@domain.com"
                className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div>
              <button
                type="button"
                className="hover:shadow-form rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none"
                onClick={handleClick}
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  )
}
