import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'

function Header(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Hackathon Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/ethglobalicon.jpeg" />
      </Head>
      <header className="header sticky top-0 bg-white shadow-md flex items-center justify-between px-8 py-02">
        <h1 className="w-3/12">
          <Link href="/">
            <Image src="/ethglobal-banner.png" alt="ETHGlobal logo" width={200} height={200}/>
          </Link>
        </h1>
      </header>
    </div>
  )
}

export default Header
